-- MySQL Script generated by MySQL Workbench
-- 01/23/16 14:53:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Quizbowl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Quizbowl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Quizbowl` ;
USE `Quizbowl` ;

-- -----------------------------------------------------
-- Table `Quizbowl`.`TrashQs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Quizbowl`.`TrashQs` ;

CREATE TABLE IF NOT EXISTS `Quizbowl`.`TrashQs` (
  `QuestionID` INT NOT NULL AUTO_INCREMENT,
  `Questions` LONGTEXT NOT NULL,
  `Answers` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`QuestionID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
